import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 */
const sidebars: SidebarsConfig = {
  homeBar: [{type: 'autogenerated', dirName:'home'}],
  studyBar: [{type: 'autogenerated', dirName:'study'}],
  tutoBar: ['tuto/tuto'],//{type: 'autogenerated', dirName:'tuto'}],
  bookBar: [{type: 'autogenerated', dirName:'book'}]
  /* tutorialSidebar: [
    'hello',
    { type: 'category', label: 'Tutorial', items: ['tutorial-basics/create-a-document'],},
  ], */
};

export default sidebars;
