import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import { SidebarItemAutogenerated } from '@docusaurus/plugin-content-docs/src/sidebars/types.js';

function auto(dirName:string):SidebarItemAutogenerated {
  return {type: 'autogenerated',dirName: dirName}
};
/**
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 */
/* tutorialSidebar: [
  'hello',
  { type: 'category', label: 'Tutorial', items: ['tutorial-basics/create-a-document'],},
], */
const homeBars: SidebarsConfig = {
  home_home: [auto('home'),],
  home_Example: [auto('Example')],
};

const mathBars:SidebarsConfig = {
  algebraBar: [auto('Math/Algebra')],
}

const physicsBars:SidebarsConfig = {
  ppBar: [auto('Physics/PP')]
}

const computerBars:SidebarsConfig = {
  
}

const tutoBars: SidebarsConfig = {
  condaBar: [auto("tuto/conda")],
  gitBar: [auto("tuto/git")],
  vscodeBar: [auto("tuto/vscode")],
  langBar: [auto("tuto/lang")],
  MDlatexBar: [auto("tuto/md+latex")],
  qeBar: [auto("tuto/QE")],
  qepwBar: [auto("tuto/QE-PW")],
  shortcutsBar: [auto("tuto/shortcuts")],
  // gdbBar: [auto("tuto/gdb")],
};

const scrBars:SidebarsConfig = {
  offsetBar: [auto('SCR/offset')],
  zcrBar: [auto('SCR/ZCR')]
}

const booksBars:SidebarsConfig = {
  electrodynamicsBar: [auto('books/electrodynamics')]
}

const sidebars:SidebarsConfig = {
  ...homeBars,
  ...mathBars,
  ...physicsBars,
  ...computerBars,
  ...tutoBars,
  ...scrBars,
  ...booksBars
};
export default sidebars;
